TwitterGeoGraph/TwitterGeoGraph/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('general.urls')),
    url(r'^twi_geo_mrv/', include('web.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^oauth', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
]

TwitterGeoGraph/general/urls.py
from django.conf.urls import url
from . import views

app_name = 'general'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^top$', views.TopView.as_view(), name="top"),
    url(r'^clawler$', views.clawlerTwitter, name="clawler"),
    url(r'^map$', views.MapView.as_view(), name="map"),
]

TwitterGeoGraph/web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'
urlpatterns = [
    url(r'^$', views.RegisterView.as_view(), name="register"),
]

TwitterGeoGraph/web/models.py
from django.db import models

# Create your models here.

TwitterGeoGraph/general/views.py
from django.views import generic
from django.conf import settings
from django.shortcuts import redirect


class TopView(generic.TemplateView):
    template_name = "top.html"


class MapView(generic.TemplateView):
    template_name = "map.html"

    def get_context_data(self, **kwargs):
        context = super(MapView, self).get_context_data(**kwargs)
        context["key"] = settings.GOOGLE_API_KEY
        return context


class IndexView(generic.TemplateView):
    template_name = "index.html"


def clawlerTwitter(request):
    # ここでtwitter認証したuserのaccess_tokenを用いて、tweepyを使用してクロールする
    # python_social_authモデルのuser_social_authsを取りたい
    #
    # （保留）
    #  test_code/test_tweepy
    #
    user = request.user
    print(user)
    return redirect('general:index')

TwitterGeoGraph/web/views.py
from django.views import generic


class RegisterView(generic.TemplateView):
    template_name = "register.html"

TwitterGeoGraph/general/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TwitterGeoGraph</title>
    {% block extra_head %}{% endblock %}
</head>
<body>
    DEBUG: user= {{user}}
    <HR>
    {% block content %}{% endblock %}
</body>
</html>

TwitterGeoGraph/general/templates/index.html
{% extends "base.html" %}

{% block content %}

<h1>Index</h1>
<HR>
※完成前に削除<br>
①register画面でtwitter認証<br>
・認証後、top画面に移動<br>
②top画面で[twitterをクロール]、[mapで確認]を選択する<br>
③[twitterをクロール]の場合、tweepyでユーザのtwitterをクロールする<br>
・クロール後、自分だけのマーカが表示されるmap画面に移動<br>
④[mapで確認]の場合、map画面に移動<br>
<HR>

<br>

①
twitterアカウントのURLから飛ばされてきた場合<br>
<a href="{% url 'web:register' %}">twitter連携ページに移動</a><br>

<br>

②
すでに連携済み<br>
<a href="{% url 'general:top' %}">トップページに移動</a><br>

<br>

{% endblock %}

TwitterGeoGraph/general/templates/map.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_head %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/map.js' %}"></script>
{% endblock %}

{% block content %}

<h1>Map</h1>
<HR>

<br>

<!-- google mapの表示 -->
<div id="mainmap"></div>

<script src="https://maps.googleapis.com/maps/api/js?key={{ key }}&callback=initMap"></script>

{% endblock %}

TwitterGeoGraph/general/templates/top.html
{% extends "base.html" %}

{% block content %}

<h1>Top</h1>
<HR>

①twitterをクロールする<br>
<a href="{% url 'general:clawler' %}">クロール</a><br>
<br>
②mapで確認する（過去の自分の結果のみ、クロールしていない場合は表示しない）<br>
<a href="{% url 'general:map' %}">マップ</a><br>
<br>
③mapで確認する（他の人の情報も確認可能、実装未定）<br>

{% endblock %}

TwitterGeoGraph/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TwitterGeoGraph</title>
    {% block extra_head %}{% endblock %}
</head>
<body>
    DEBUG: user= {{user}}
    <HR>
    {% block content %}{% endblock %}
</body>
</html>

TwitterGeoGraph/web/templates/register.html
{% extends "base.html" %}

{% block content %}

<h1>Register</h1>
<HR>

<ul>
    {% if user and not user.is_anonymous %}
        <li>
            <a>Hello {{ user.get_full_name|default:user.username }}!</a>
        </li>
        <li>
            <a href="{% url 'auth:logout' %}?next={% url 'web:register' %}">Logout</a>
        </li>
    {% else %}
        <li>
            <a href="{% url 'social:begin' 'twitter' %}?next={% url 'general:top' %}">Login with Twitter</a>
        </li>
    {% endif %}
</ul>

{% endblock %}